
name: wazo-asterisk-reduce-events
namespace: wazocommunication
version: 1.0.0
author: Wazo authors
display_name: Asterisk Events Reduction
min_wazo_version: 23.01
tags:
  - asterisk
  - mitigation
homepage: https://github.com/wazo-communication/wazo-asterisk-reduce-events-plugin
